FROM python:3.13-slim-trixie
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --group migrate

COPY ./apps ./apps
COPY ./alembic ./alembic
COPY ./alembic.ini ./alembic.ini

CMD ["uv", "run", "--no-sync","alembic", "upgrade", "head"]
