[project]
name = "ticketbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.5",
    "fastapi>=0.117.1",
    "httpx>=0.28.1",
    "playwright>=1.55.0",
    "pydantic[email]>=2.11.9",
    "pytest>=8.4.2",
    "sqlalchemy>=2.0.43",
    "uvicorn>=0.36.0",
]
